# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# Refer to https://github.com/toml-lang/toml for detailed TOML docs.

ignored = ["k8s.io/cloud-provider-vsphere"]

[[constraint]]
  name = "github.com/rexray/gocsi"
  branch = "master"

[[constraint]]
  name = "github.com/container-storage-interface/spec"
  version = "1.0.0"

[[constraint]]
  name = "github.com/akutz/gofsutil"
  version = "0.1.2"

[[constraint]]
  name = "k8s.io/klog"
  version = "0.2.0"

[[override]]
  branch = "master"
  name = "github.com/mitchellh/mapstructure"

[[override]]
  name = "github.com/docker/distribution"
  branch = "master"

[[override]]
  name = "github.com/vmware/govmomi"
  branch = "master"

[[override]]
  name = "github.com/json-iterator/go"
  version = "1.1.4"

[[override]]
  name = "github.com/spf13/cobra"
  version = "0.0.2"

[[override]]
  branch = "master"
  name = "golang.org/x/net"

[[override]]
  name = "google.golang.org/grpc"
  version = "1.11.1"

[[override]]
  name = "gopkg.in/gcfg.v1"
  version = "1.2.1"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.0"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.0"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.11.0"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.0"

[[override]]
  name = "k8s.io/kubernetes"
  version = "1.11.0"

[prune]
  go-tests = true
  unused-packages = true
