{{- $config := .Values.config -}}
{{- if .Values.global }}
{{- if .Values.global.config }}
{{- $config = mergeOverwrite (deepCopy .Values.config) .Values.global.config -}}
{{- end }}
{{- end }}
{{- if $config.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $config.name | default "cloud-config" }}
  labels:
    app: {{ template "cpi.name" . }}
    vsphere-cpi-infra: cloud-config
    component: cloud-controller-manager
  namespace: {{ .Release.Namespace }}
data:
  vsphere.conf: |
    # Global properties in this section will be used for all specified vCenters unless overriden in VirtualCenter section.
    global:
      port: 443
      {{- if $config.thumbprint }}
      thumbprint: {{ $config.thumbprint }}
      {{- else }}
      # set insecure-flag to true if the vCenter uses a self-signed cert
      insecureFlag: true
      {{- end }}
      # settings for using k8s secret
      secretName: {{ $config.secret.name }}
      secretNamespace: {{ .Release.Namespace }}

    # vcenter section
    vcenter:
      {{ $config.vcenter }}:
        server: {{ $config.vcenter }}
        datacenters:
          - {{ $config.datacenter }}

    # labels for regions and zones
    labels:
      region: {{ $config.region }}
      zone: {{ $config.zone }}
{{- end -}}
