name: Weekly security scan

on:
  schedule:
    # Cron for every Monday at 12:00 UTC.
    - cron: "0 12 * * 1"

# Remove all permissions from GITHUB_TOKEN except metadata.
permissions: {}

jobs:
  scan:
    strategy:
      fail-fast: false
      matrix:
        branch: [ master, release-1.34, release-1.33, release-1.32 ]
    name: Trivy
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # tag=v4.2.2
      with:
        ref: ${{ matrix.branch }}
    - name: Calculate go version
      id: vars
      run: echo "go_version=$(make go-version)" >> $GITHUB_OUTPUT
    - name: Set up Go
      uses: actions/setup-go@c0137caad775660c0844396c52da96e560aba63d # tag=v5.1.0
      with:
        go-version: ${{ steps.vars.outputs.go_version }}
    - name: Run verify security target
      run: make verify-security
